<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<html lang="en">
<head>
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
 </script>
<script type="text/javascript">
function setData(value){
	alert(value);
	//$('#searchcompany').value(value)
};

function getCompanyData(){
	
	$.ajax({
    url : "/getdata?data="+$('#searchresult option:selected').text(),
    type : "POST",
    async : false,
    success : function(data) {
    	
    	 var len = data.length
         /* for (var i=0; i<len; ++i) {
                var employeeFirstName =  data[i]
                //set it to some DIV, or do the processing you want
         } */
    	 /* $('#searchresult').val(data); */
    	 //$('#searchresult').html(data);
    	 //$('#content').html("");
    	 //$('#searchresult').append('<select>') 
    	 	$('#content').val(data);
    	 /* for(i in data){
    		 
    		 $('#searchresult').append('<option value=companyname>'+ data[i]+'</option>')
    	 } */
    	 //$('#searchresult').append('</select>')
    },
	error: function(XMLHttpRequest, textStatus, errorThrown) { 
        alert("Status: " + textStatus); alert("Error: " + errorThrown); 
    }    
})
	
};
function alertData(){
	/* selectedvalue=$('#searchresult').value()
	alert(selectedvalue); */
	alert("hi!"+$('#searchresult option:selected').text());
}
function showData(value){ 
$.ajax({
    url : "/search?data="+value,
    type : "POST",
    async : true,
    success : function(data) {
    	 var len = data.length
         /* for (var i=0; i<len; ++i) {
                var employeeFirstName =  data[i]
                //set it to some DIV, or do the processing you want
         } */
    	 /* $('#searchresult').val(data); */
    	 //$('#searchresult').html(data);
    	 $('#searchresult').html("");
    	 //$('#searchresult').append('<select>') 
    	 	
    	 for(i in data){
    		 
    		 $('#searchresult').append('<option value=companyname>'+ data[i]+'</option>')
    	 }
    	 //$('#searchresult').append('</select>')
    }
});
}
</script>
<!-- <style>
#searchresult{height:200px; overflow-y:auto; border: 1px solid #ddd; padding: 10px; margin-top: 10px; background-color:#eee}
</style> -->
</head>
<body><%-- 
    <h1>${message}</h1>

    <spring:url value="/test.txt" htmlEscape="true" var="springUrl" />
    <c:url value="/test.txt" var="url"/>

    <p><a href="${springUrl}">URL generated by Spring</a></p>
    <p><a href="${url}">URL generated by JSTL</a></p>
 --%>
 
 <form id="upload-file-form">
  <label for="searchcompany">Search for company:</label>
  <input id="searchcompany" type="search"  onkeyup="showData(this.value);" height="1080"/>
 	 
  <select id="searchresult" >
  
  </select >
  <input type="button" value="Submit" onclick="getCompanyData();"/>
</form>

<div id="content"></div>
 </body>

</html>